services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./nginx
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "443:443"
    restart: always
    networks:
      - inception-network

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    restart: always
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
    secrets:
      - mysql_password
    restart: always
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

secrets:
  mysql_password:
    file: ${SECRETS_PATH}/mysql_password.txt
  mysql_root_password:
    file: ${SECRETS_PATH}/mysql_root_password.txt
